/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dibujos;

import java.awt.Color;
import java.awt.Graphics;
/**
 *
 * @author kenyv
 */
public class CompOne extends javax.swing.JApplet {

    /**
     * Initializes the applet CompOne
     */
    @Override
    public void init() {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param g
     */
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        //Cielo
        g.setColor(Color.white);
        g.fillRect(0, 0, 500, 400);
        //Sol
        g.setColor(Color.yellow);
        g.fillOval(55, 50, 50, 75);
        //El hermoso mar
        g.setColor(Color.blue);
        g.fillRect(0, 100, 500, 200);
        //La arena
        //La funcion decode() recibe un string numerico que
        //representa el codigo del color cafe como int de 24 bits
        g.setColor(Color.decode("10046464"));
        g.fillRect(0, 250, 500, 150);
        g.setColor(Color.black);
        g.drawString("Que bello atardecer", 295, 300);
        //Una persona
        g.drawOval(400, 300, 25, 25);
        g.drawLine(413, 325, 413, 375);
        g.drawArc(403, 375, 20, 50, 2, 180);
        g.drawArc(403, 340, 20, 50, 2, 180);
        //Aves
        g.drawArc(300, 45, 50, 20, 10, 150);
        g.drawArc(350, 45, 50, 20, 30, 180);
        g.drawArc(200, 30, 50, 20, 10, 150);
        g.drawArc(250, 30, 50, 20, 30, 180);
        g.drawArc(100, 45, 50, 20, 10, 150);
        g.drawArc(150, 45, 50, 20, 30, 180);
        //una isla
        g.setColor(Color.decode("10046464"));
        g.fillArc(350, 150, 100, 20, 0, 180);
        //palmera
        g.fillArc(370, 110, 20, 100, 10, 85);
        g.setColor(Color.green);
        g.fillArc(382, 110, 38, 10, 30, 180);
        g.fillArc(379, 108, 60, 5, 45, 160);
        g.fillArc(350, 115, 38, 10, 30, 180);
        g.fillArc(355, 110, 30, 5, 45, 160);
        //ballena
        g.setColor(Color.decode("2105376"));
        g.fillArc(115, 125, 80, 30, 0, 180);
        g.fillArc(135, 118, 80, 30, 90, 90);
        g.setColor(Color.WHITE);
        g.fillOval(125, 132, 13, 5);
        
    }
    
}
